framework:
    enabled_locales: ['en', 'fr', 'de']
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
