# Production environment override
services:
  app:
    build:
      context: .
      target: frankenphp_prod
    environment:
      NODE_ENV: production
      APP_ENV: production
      APP_DEBUG: false
      MAIL_MAILER: resend
      RESEND_KEY: ${RESEND_KEY}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
