services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - caddy_data:/data 
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
