# Production environment override
services:
  app:
    build:
      context: .
      target: frankenphp_prod
    environment:
      NODE_ENV: production
      APP_ENV: production
      APP_DEBUG: false